window.onload = function startup() {
    
}

function alert_not_implemented() {
    alert('Function not implemented')
}


function fetchLatestRelease() { // Generated by ChatGPT lol
    fetch('https://api.github.com/repos/thekliko/klikos-modloader/releases/latest')
        .then(response => response.json())
        .then(data => {
            const downloadUrl = data.assets[0].browser_download_url;
            window.location.href = downloadUrl;
        })
        .catch(error => {
            console.error('Error fetching latest release:', error);
            alert('Error fetching latest release')
        });
}